name: CI TalentoLab # Nombre descriptivo del workflow
on: # EVENTOS: cuándo se ejecuta
  push:
  branches: [ main, develop ]
  pull_request:
  branches: [ main, develop ]
jobs:
  test: # JOB principal
  runs-on: ubuntu-latest # RUNNER: máquina Ubuntu
  env: # VARIABLES de entorno
  PYTHON_VERSION: '3.12'
  PIP_CACHE: ~/.cache/pip
steps: # STEPS: comandos individuales
  # 1 · Checkout
- name: Checkout código
  uses: actions/checkout@v4 # Acción del Marketplace
  # 2 · Cache de pip
- name: Cache dependencias
  uses: actions/cache@v4
  with:
  path: ${{ env.PIP_CACHE }}
  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  # 3 · Setup Python
- name: Instalar Python ${{ env.PYTHON_VERSION }}
  uses: actions/setup-python@v5
  with:
  python-version: ${{ env.PYTHON_VERSION }}
  # 4 · Instalar dependencias
- name: Install dependencies
  run: pip install -r requirements.txt
  # 5 · Ejecutar tests UI + API + BDD
- name: Run Pytest & Behave
  run: |
    python3 run_test.py
# 6 · Subir artefactos (reportes + logs)
- name: Upload HTML report
  uses: actions/upload-artifact@v4
  with:
    name: html-report
    path: reports/
- name: Upload Suite Log
  uses: actions/upload-artifact@v4
  with:
    name: suite-log
    path: logs/
